pool:
  vmImage: ubuntu-latest
pr: none

steps:
- script: docker info
  displayName: 'Info'

- script: |
    docker-compose down
    docker-compose build --pull
    docker-compose pull
  displayName: 'Build Tests'

- script: docker-compose run --rm tests71
  displayName: 'Run Tests PHP 7.1'
  env:
    TEST_TOPIC_ENDPOINT: $(TEST_TOPIC_ENDPOINT)
    TEST_TOPIC_KEY: $(TEST_TOPIC_KEY)

- script: docker-compose run --rm tests72
  displayName: 'Run Tests PHP 7.2'
  env:
    TEST_TOPIC_ENDPOINT: $(TEST_TOPIC_ENDPOINT)
    TEST_TOPIC_KEY: $(TEST_TOPIC_KEY)

- script: docker-compose run --rm tests73
  displayName: 'Run Tests PHP 7.3'
  env:
    TEST_TOPIC_ENDPOINT: $(TEST_TOPIC_ENDPOINT)
    TEST_TOPIC_KEY: $(TEST_TOPIC_KEY)

- script: docker-compose run --rm tests74
  displayName: 'Run Tests PHP 7.4'
  env:
    TEST_TOPIC_ENDPOINT: $(TEST_TOPIC_ENDPOINT)
    TEST_TOPIC_KEY: $(TEST_TOPIC_KEY)
    # For Codeclimate:
    GIT_COMMIT_SHA: $(Build.SourceVersion)
    GIT_BRANCH: $(Build.SourceBranch)
    CC_TEST_REPORTER_ID: $(CC_TEST_REPORTER_ID)

- task: PublishTestResults@2
  displayName: 'Publish Test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/logs/*.xml'
