version: "3"
services:
  # for development purposes
  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_TOPIC_ENDPOINT
      - TEST_TOPIC_KEY
      - GIT_BRANCH
      - GIT_COMMIT_SHA
    command: ["composer", "ci"]

  tests-local:
    <<: *tests
    volumes:
      - ./:/code
